// Generated by https://quicktype.io

export interface IOrder {
  id:     number;
  turno:  number;
  // mesa:   number;
  mesero: string;
  estado: string;
  pago:   string;
  pedido: Pedido[];
  notas:  string;
}

export interface Pedido {
  id:       number;
  producto: string;
  precio:   number;
  cantidad: number;
}
